* cljsword

This started out as a proof of concept for interfacing Crosswire's jsword with Clojure. It's become more of a personal peorject now, and as such, is more useful as a Clojure library. Jsword is not yet available in a maven repository, so it will require compiling, and installing that library on your own. But don't be afraid, I've tried to make it super easy with these instructions.

** Installation
*** You'll need:
    1. Java 8 or higher
    2. Maven 3+
    3. Leiningen 2+
    4. An installation of Sword Bibles/texts/commentaries.

    This library does not (yet) implement any of the JSword API's for downloading and installing Bibles and other texts. That functionality is not very high on my lisp of priorities, as it is totally out of scope for how I am planning on using this library. You can, however, use Java interop to use these API's yourself, and if you think it might be useful to others, feel free to submit a PR for it.

    Aside from that, you'll need to install a few texts to make this work. On Ubuntu/Debian systems it is as easy as:
    #+BEGIN_SRC shell
    apt install sword-text-kjv
    #+END_SRC
    This installs the King James Version bible in Sword format, suitable for use with this library. This will give you a fairly comprehensive installation including Strongs concordance for both Greek and Hebrew words, the Greek Textus Receptus New Testament and the Westminster Leningrad Hebrew Old Testament.
    #+BEGIN_SRC shell
    apt install sword-text-kjv sword-dict-strongs-greek sword-dict-strongs-hebrew sword-text-tr sword-text-wlc
    #+END_SRC

    On other systems, including MacOS and Windows, you can install Xiphos or Bibletime, and use these programs to browse and install a vast array of other texts, including the ones above.

    Ubuntu/Debian users can just run ~apt install xiphos~ or ~apt install bibletime~. I am not sure if these programs are available for Homebrew and Coco, your mileage may vary.
*** Install Latest Jsword SNAPSHOT with Maven
    #+BEGIN_SRC shell
    git clone https://github.com/crosswire/jsword.git
    cd jsword
    mvn install -DskipTests=true
    #+END_SRC

    If, for whatever reason, the latest JSword ceases to work with this code,
    you can download my fork of Jsword and switch to the v2.1 branch and install
    it from there.
    #+BEGIN_SRC shell
    https://github.com/timotheosh/jsword.git
    cd jsword
    git checkout v2.1
    mvn install -DskipTests=true
    #+END_SRC

    Then get cljsword
    #+BEGIN_SRC shell
    git clone https://github.com/timotheosh/cljsword.git
    cd cljsword
    lein install
    #+END_SRC
** Usage
   Add ~[cljsword "0.2.0-SNAPSHOT"]~ (or whatever version you find defined in the latest project.clj file for this project you have downloaded).
   And use like so:
   #+BEGIN_SRC clojure
   (require 'cljsword.core)
   (cljsword.core/get-text "KJV" "psa23:1-4")
   "A Psalm of David . The Lord is my shepherd ; I shall not want . He maketh me to lie down in green pastures : he leadeth me beside the still waters . He restoreth my soul : he leadeth me in the paths of righteousness for his name’s sake. Yea, though I walk through the valley of the shadow of death , I will fear no evil : for thou art
   with me; thy rod and thy staff they comfort me."
   #+END_SRC

** License

Copyright © 2017-2019 Tim Hawes

Distributed under the MIT License.
